
- name: Generate SSH key pair for user
  ansible.builtin.openssh_keypair:
    path: "/home/{{ ansible_user }}/.ssh/id_rsa"
    type: rsa
    size: 4096
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  register: ssh_keygen_result

- name: Display public key
  debug:
    var: ssh_keygen_result.public_key
